# Generated by Django 4.2.7 on 2023-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testas', '0002_choice_response_remove_question_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choice',
            field=models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')]),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
