# Generated by Django 4.2.7 on 2023-12-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testas', '0006_personalityadvice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
    ]
